---
- name: set gpg key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: add repository
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main'
    filename: teams
    state: present
    update_cache: yes
