---
# tasks file for ms-teams

- name: Include tasks for "{{ ansible_os_family }}"
  include: "{{ ansible_os_family | lower }}.yml"

- name: install teams
  apt:
    name: teams
    update_cache: true
  when:
    - teams_install | bool

- name: install teams insiders
  apt:
    name: teams-insiders
    update_cache: true
  when:
    - teams_insiders_install | bool
